### ISSUE TITLE
Not receiving folder list from hosted Razuna

### ISSUE THREAD

**Issue by nddejong** [razuna/razuna-mura-plugin#2]
When I click on the Razuna link next to the summary box I get an empty box with no folder list.  I am using a free 30 day trial of Razuna.  I tried leaving the DAM path blank and with just a "/". For API Key I put "asd" like you did in your YouTube video.

**Comment by JasPanesar** [comment]
Hi, is this plugin still being maintained to work with the latest Mura?  I'm looking to use it but don't want to get into compatibility issues.

**Comment by thenitai** [comment]
Hi Jas,

This plugin has been maintained by a third party. I haven't seen any updates. From our side, i.e. Razuna, it should still work.

**Comment by JasPanesar** [comment]
Awesome Nitai, thanks! Will give it a go.

**Comment by thenitai** [comment]
Let me know if you run into anything. We sure can figure it out :)

**Comment by mcbitss** [comment]
@JasPanesar This is moved as a part of MuraCMS core https://github.com/blueriver/MuraCMS/commit/9ba2219d08f3431df11bf2b266dc077a977301be

So you need not to use this plugin

**Comment by cfmitrah** [comment]
@JasPanesar This is moved as a part of MuraCMS core https://github.com/blueriver/MuraCMS/commit/9ba2219d08f3431df11bf2b266dc077a977301be

So you need not to use this plugin

**Comment by thenitai** [comment]
@cfmitrah Are you saying that this is now enabled within MuraCMS, i.e. Razuna works out of the box?

**Comment by JasPanesar** [comment]
@cfmitrah Thanks for the tip.

@thenitai I installed the latest version of Mura and was able to access the integrated (since v6.2) Razuna functionality to configure with the following steps.

1) edit config/system.ini.cfm to add 
`razuna=true`
underneath [production]

2) Mura Menu > Global Settings > Reload Application

3) Mura Menu > Site Settings > Default Site > Access down arrow shaped menu at the top right corner, and you should see "Razuna" there to complete the connection to Mura. Once I get this running I'll add a doc somewhere on this project or in a gist.

J

**Comment by thenitai** [comment]
@JasPanesar Great 👍

**Comment by mcbitss** [comment]
https://github.com/razuna/razuna-mura-plugin/issues/2#issuecomment-361352585 

Yes, @thenitai Razuna integration will work, out of box of Mura installation, no need to install this plugin

**Comment by JasPanesar** [comment]
Hi @cfmitrah  - Installed Mura 7.0.7077 and have the built-in Razuna integration connected OK.  

Looks like there might be a snag in the UI with selecting an image from Razuna - the Razuna modal is below the Mura Image select modal.  I'm assuming the razuna plugin wouldn't fare any better and this might be a display artifact from the Admin UI changes in 7.0.7077

Test Razuna server (1.9.5) and Test Mura server (7.0.7077) in this case are both hosted on a VM and are working fine on their own.  Open to any ideas, just thought I'd ping and hope it's ok.

https://screencast.com/t/zbJ93hmRwvS

**Comment by cfmitrah** [comment]
@JasPanesar Please file an issue in MuraCMS repo, whenever I have some free time, I will try to fix it & make a PR to their repo against your issue

**Comment by JasPanesar** [comment]
Thanks I was thinking of doing the same - searching for Mura and Razuna 
brings up this repo so I thought I'd mention it here too in case anyone 
looks here. Haven't had a chance to look at the bug yet.
